export enum Statut {
    DIRECTEUR = "DIRECTEUR" ,
	DIRECTEUR_DE_DEPARTMENT = "DIRECTEUR_DE_DEPARTMENT" ,
    DIRECTEUR_DES_ETUDES="DIRECTEUR_DES_ETUDES",
    DIRECTEUR_DES_STAGES="DIRECTEUR_DES_STAGES",
    NONE="NONE"
}